In [6]:
import numpy as np
import torch

data = [[2, 3], [4, 5]]
t_data = torch.tensor(data)
t_data

tensor([[2, 3],
        [4, 5]])

In [7]:
data = np.ones((2,3))
t_data = torch.from_numpy(data)
t_data

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [8]:
t_data = torch.rand((2,3))
t_data

tensor([[0.9507, 0.6137, 0.5276],
        [0.6441, 0.7925, 0.9614]])

In [9]:
t_data.shape

torch.Size([2, 3])

In [10]:
t_data.size()

torch.Size([2, 3])

In [11]:
t_data.dtype

torch.float32

In [12]:
t_data.device

device(type='cpu')

In [13]:
n_data = t_data.numpy()
n_data

array([[0.9506878 , 0.6137394 , 0.5275892 ],
       [0.64407694, 0.79254174, 0.9614004 ]], dtype=float32)

numpy的shape和size

In [21]:
n_data.shape

(2, 3)

In [23]:
n_data.size

6

In [14]:
mul_data = t_data.mul(t_data)
mul_data

tensor([[0.9038, 0.3767, 0.2784],
        [0.4148, 0.6281, 0.9243]])

In [15]:
add_data = t_data.add_(1)
add_data

tensor([[1.9507, 1.6137, 1.5276],
        [1.6441, 1.7925, 1.9614]])

In [16]:
data = torch.tensor([[1,2],[2,4]])
data.add_(1)
print(data)

tensor([[2, 3],
        [3, 5]])


In [17]:
data.device

device(type='cpu')

In [18]:
if torch.cuda.is_available():
    data = data.to('cuda')
print(data.device)

cuda:0


In [19]:
# shape device dtype size()